export default {
    PRIMARY_COLOR: '#0abde3',
    INPUT_LABEL_COLOR: '#fff',
    ICON_COLOR: '#273c75',

    // Fonts
    FONT_SIZE_NORMAL: 13,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_NORMAL: '400',
    FONT_WEIGHT_MEDIUM: '600',
    FONT_WEIGHT_BOLD: '800',
    FONT_WEIGHT_xBOLD: '900'
}